# Generated by Django 6.1 on 2026-08-07 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('player1_name', models.CharField(max_length=100)),
                ('player2_name', models.CharField(max_length=100)),
                ('player3_name', models.CharField(max_length=100)),
                ('player4_name', models.CharField(max_length=100)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('player1_score', models.PositiveIntegerField(default=0)),
                ('player2_score', models.PositiveIntegerField(default=0)),
                ('player3_score', models.PositiveIntegerField(default=0)),
                ('player4_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.game')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('game', 'round_number')},
            },
        ),
    ]
